(package "liquidmetal"
         "1.3.0"
         "A mimetic poly-alloy of the Quicksilver scoring algorithm")

(website-url "https://github.com/jcs-elpa/liquidmetal")
(keywords "fuzzy" "matching")

(package-file "liquidmetal.el")

(source "melpa")

(depends-on "emacs" "24.4")

(development
 (depends-on "ert-runner"))

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
